from __future__ import annotations

import argparse
import json
from datetime import datetime
from pathlib import Path

import pandas as pd

EMPTY_VALUES = {"", "nan", "none"}
MARKER_START = "<!-- AUTO_DECISION_TRACE_START -->"
MARKER_END = "<!-- AUTO_DECISION_TRACE_END -->"
ANALYSIS_MARKER_START = "<!-- AUTO_ANALYSIS_TRACE_START -->"
ANALYSIS_MARKER_END = "<!-- AUTO_ANALYSIS_TRACE_END -->"
INSERT_BEFORE_HEADING = "## 3. Extraction sample"


def normalize(value: object) -> str:
    if value is None:
        return ""
    try:
        if pd.isna(value):
            return ""
    except (TypeError, ValueError):
        pass
    text = str(value).strip()
    if text.lower() in EMPTY_VALUES:
        return ""
    return text


def non_empty_rows(df: pd.DataFrame) -> pd.DataFrame:
    if df.empty:
        return df

    def is_non_empty(row: pd.Series) -> bool:
        return any(normalize(cell) for cell in row)

    mask = df.apply(is_non_empty, axis=1)
    return df[mask].copy()


def display_value(value: object) -> str:
    text = normalize(value)
    if not text:
        return "—"
    return text.replace("|", r"\|").replace("\n", " ")


def latex_escape(value: object) -> str:
    text = normalize(value)
    if not text:
        return "---"
    escaped = text.replace("\n", " ").replace("\r", " ")
    escaped = escaped.replace("\\", r"\textbackslash{}")
    escaped = escaped.replace("&", r"\&")
    escaped = escaped.replace("%", r"\%")
    escaped = escaped.replace("$", r"\$")
    escaped = escaped.replace("#", r"\#")
    escaped = escaped.replace("_", r"\_")
    escaped = escaped.replace("{", r"\{")
    escaped = escaped.replace("}", r"\}")
    escaped = escaped.replace("~", r"\textasciitilde{}")
    escaped = escaped.replace("^", r"\textasciicircum{}")
    return escaped


def build_decision_trace_block(
    decision_df: pd.DataFrame,
    *,
    decision_log_path_display: str,
    max_rows: int,
) -> str:
    rows = non_empty_rows(decision_df)
    available_columns = {column for column in rows.columns}

    lines: list[str] = []
    lines.append(MARKER_START)
    lines.append("### Decision trace log (auto-export)")
    lines.append("")
    lines.append("Primary source:")
    lines.append("")
    lines.append(f"- `{decision_log_path_display}`")
    lines.append("")
    lines.append(
        "This subsection is auto-generated from the decision log to document who made each decision and why."
    )
    lines.append("")

    if rows.empty:
        lines.append("No decision-log rows found yet.")
        lines.append(MARKER_END)
        return "\n".join(lines)

    include_count = 0
    exclude_count = 0
    uncertain_count = 0
    if "decision" in available_columns:
        decisions = rows["decision"].fillna("").astype(str).str.strip().str.lower()
        include_count = int(decisions.isin({"include", "included", "yes", "y", "1", "true"}).sum())
        exclude_count = int(decisions.isin({"exclude", "excluded", "no", "n", "0", "false"}).sum())
        uncertain_count = int(decisions.isin({"maybe", "uncertain", "pending"}).sum())

    lines.append("Snapshot:")
    lines.append("")
    lines.append(f"- Rows logged: {int(rows.shape[0])}")
    lines.append(f"- Include decisions: {include_count}")
    lines.append(f"- Exclude decisions: {exclude_count}")
    lines.append(f"- Uncertain/maybe decisions: {uncertain_count}")
    lines.append("")
    lines.append("| Record ID | Stage | Decision | Reason | Reviewer |")
    lines.append("| --- | --- | --- | --- | --- |")

    trimmed_rows = rows.head(max_rows)
    for _, row in trimmed_rows.iterrows():
        lines.append(
            "| "
            + " | ".join(
                [
                    display_value(row.get("record_id", "")),
                    display_value(row.get("stage", "")),
                    display_value(row.get("decision", "")),
                    display_value(row.get("reason", "")),
                    display_value(row.get("reviewer", "")),
                ]
            )
            + " |"
        )

    if int(rows.shape[0]) > max_rows:
        lines.append("")
        lines.append(
            f"_Table truncated to first {max_rows} rows for readability; full trace is in `{decision_log_path_display}`._"
        )

    lines.append(MARKER_END)
    return "\n".join(lines)


def build_latex_decision_trace_table(
    decision_df: pd.DataFrame,
    *,
    decision_log_path_display: str,
    max_rows: int,
) -> str:
    generated_at = datetime.now().strftime("%Y-%m-%d %H:%M")
    rows = non_empty_rows(decision_df)

    lines: list[str] = []
    lines.append("% Auto-generated by 03_analysis/transparency_appendix_decision_trace.py")
    lines.append(f"% Source: {decision_log_path_display}")
    lines.append(f"% Generated: {generated_at}")
    lines.append(r"\begin{table}[htbp]")
    lines.append(r"\centering")
    lines.append(r"\caption{Decision trace log by record/stage (auto-generated)}")
    lines.append(r"\label{tab:decision_trace_log}")
    lines.append(r"\small")
    lines.append(r"\begin{tabular}{llllp{0.30\textwidth}}")
    lines.append(r"\toprule")
    lines.append(r"Record ID & Stage & Decision & Reviewer & Reason \\")
    lines.append(r"\midrule")

    if rows.empty:
        lines.append(r"--- & --- & --- & --- & No decision-log rows found yet. \\")
    else:
        for _, row in rows.head(max_rows).iterrows():
            lines.append(
                f"{latex_escape(row.get('record_id', ''))} & "
                f"{latex_escape(row.get('stage', ''))} & "
                f"{latex_escape(row.get('decision', ''))} & "
                f"{latex_escape(row.get('reviewer', ''))} & "
                f"{latex_escape(row.get('reason', ''))} \\\\"
            )

    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")
    if int(rows.shape[0]) > max_rows:
        lines.append(
            rf"\vspace{{0.25em}}\\{{\footnotesize Table truncated to first {max_rows} rows; full trace in \texttt{{02\_data/processed/decision\_log.csv}}.}}"
        )
    lines.append(r"\end{table}")
    lines.append("")
    return "\n".join(lines)


def analysis_trace_rows(payload: dict[str, object]) -> list[dict[str, object]]:
    indexed_rows: list[tuple[int, dict[str, object]]] = []

    for key, value in payload.items():
        if not key.startswith("outcome_") or not isinstance(value, dict):
            continue

        suffix = key.replace("outcome_", "", 1)
        try:
            index = int(suffix)
        except ValueError:
            continue

        indexed_rows.append((index, value))

    indexed_rows.sort(key=lambda item: item[0])

    rows: list[dict[str, object]] = []
    for _, row in indexed_rows:
        rows.append(row)
    return rows


def display_list(values: object) -> str:
    if not isinstance(values, list):
        return display_value(values)

    cleaned = [normalize(item) for item in values if normalize(item)]
    if not cleaned:
        return "—"
    return ", ".join(cleaned).replace("|", r"\|")


def load_analysis_trace_payload(path: Path) -> tuple[dict[str, object] | None, str]:
    if not path.exists():
        return None, "not_found"

    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return None, "invalid_json"

    if not isinstance(payload, dict):
        return None, "invalid_format"

    return payload, "ok"


def build_analysis_trace_block(
    payload: dict[str, object] | None,
    *,
    source_display: str,
    status: str,
    max_rows: int,
) -> tuple[str, int]:
    lines: list[str] = []
    lines.append(ANALYSIS_MARKER_START)
    lines.append("### Analysis traceability (auto-export)")
    lines.append("")
    lines.append("Primary source:")
    lines.append("")
    lines.append(f"- `{source_display}`")
    lines.append("")
    lines.append(
        "This subsection is auto-generated from analysis trace artifacts to document which studies were pooled for each outcome and which were excluded."
    )
    lines.append("")

    if status == "not_found":
        lines.append("Analysis trace artifact not found yet.")
        lines.append(ANALYSIS_MARKER_END)
        return "\n".join(lines), 0

    if status in {"invalid_json", "invalid_format"}:
        lines.append("Analysis trace artifact is present but could not be parsed.")
        lines.append(ANALYSIS_MARKER_END)
        return "\n".join(lines), 0

    rows = analysis_trace_rows(payload or {})
    if not rows:
        lines.append("No per-outcome analysis-trace rows found yet.")
        lines.append(ANALYSIS_MARKER_END)
        return "\n".join(lines), 0

    unique_included: set[str] = set()
    unique_excluded: set[str] = set()
    outcomes_with_exclusions = 0

    for row in rows:
        included_items = row.get("studies", [])
        excluded_items = row.get("excluded", [])

        if isinstance(included_items, list):
            unique_included.update(normalize(item) for item in included_items if normalize(item))
        if isinstance(excluded_items, list):
            filtered_excluded = [normalize(item) for item in excluded_items if normalize(item)]
            if filtered_excluded:
                outcomes_with_exclusions += 1
                unique_excluded.update(filtered_excluded)

    lines.append("Snapshot:")
    lines.append("")
    lines.append(f"- Outcomes logged: {len(rows)}")
    lines.append(f"- Outcomes with exclusions: {outcomes_with_exclusions}")
    lines.append(f"- Unique included studies: {len(unique_included)}")
    lines.append(f"- Unique excluded studies: {len(unique_excluded)}")
    lines.append("")
    lines.append("| Outcome | Model | Included studies | Excluded studies | Reason excluded |")
    lines.append("| --- | --- | --- | --- | --- |")

    for row in rows[:max_rows]:
        lines.append(
            "| "
            + " | ".join(
                [
                    display_value(row.get("outcome", "")),
                    display_value(row.get("model", "")),
                    display_list(row.get("studies", [])),
                    display_list(row.get("excluded", [])),
                    display_value(row.get("reason_excluded", "")),
                ]
            )
            + " |"
        )

    if len(rows) > max_rows:
        lines.append("")
        lines.append(
            f"_Table truncated to first {max_rows} rows for readability; full trace is in `{source_display}`._"
        )

    lines.append(ANALYSIS_MARKER_END)
    return "\n".join(lines), len(rows)


def analysis_trace_cell(value: object) -> str:
    if isinstance(value, list):
        cleaned = [normalize(item) for item in value if normalize(item)]
        if not cleaned:
            return "---"
        return latex_escape(", ".join(cleaned))

    text = normalize(value)
    if not text:
        return "---"
    return latex_escape(text)


def build_latex_analysis_trace_table(
    payload: dict[str, object] | None,
    *,
    source_display: str,
    status: str,
    max_rows: int,
) -> str:
    generated_at = datetime.now().strftime("%Y-%m-%d %H:%M")
    rows = analysis_trace_rows(payload or {}) if status == "ok" else []

    lines: list[str] = []
    lines.append("% Auto-generated by 03_analysis/transparency_appendix_decision_trace.py")
    lines.append(f"% Source: {source_display}")
    lines.append(f"% Generated: {generated_at}")
    lines.append(r"\begin{table}[htbp]")
    lines.append(r"\centering")
    lines.append(r"\caption{Outcome-level analysis traceability (auto-generated)}")
    lines.append(r"\label{tab:analysis_trace_log}")
    lines.append(r"\small")
    lines.append(r"\begin{tabular}{llp{0.22\textwidth}p{0.16\textwidth}p{0.22\textwidth}}")
    lines.append(r"\toprule")
    lines.append(r"Outcome & Model & Included studies & Excluded studies & Reason excluded \\")
    lines.append(r"\midrule")

    if status == "not_found":
        lines.append(r"--- & --- & --- & --- & Analysis trace artifact not found yet. \\")
    elif status in {"invalid_json", "invalid_format"}:
        lines.append(
            r"--- & --- & --- & --- & Analysis trace artifact is present but could not be parsed. \\"
        )
    elif not rows:
        lines.append(r"--- & --- & --- & --- & No per-outcome analysis-trace rows found yet. \\")
    else:
        for row in rows[:max_rows]:
            lines.append(
                f"{analysis_trace_cell(row.get('outcome', ''))} & "
                f"{analysis_trace_cell(row.get('model', ''))} & "
                f"{analysis_trace_cell(row.get('studies', []))} & "
                f"{analysis_trace_cell(row.get('excluded', []))} & "
                f"{analysis_trace_cell(row.get('reason_excluded', ''))} \\\\"
            )

    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")
    if len(rows) > max_rows:
        lines.append(
            rf"\vspace{{0.25em}}\\{{\footnotesize Table truncated to first {max_rows} rows; full trace in \texttt{{03\_analysis/outputs/analysis\_trace.json}}.}}"
        )
    lines.append(r"\end{table}")
    lines.append("")
    return "\n".join(lines)


def update_appendix_text(
    appendix_text: str,
    block: str,
    *,
    marker_start: str,
    marker_end: str,
) -> tuple[str, str]:
    start_index = appendix_text.find(marker_start)
    end_index = appendix_text.find(marker_end)
    if start_index != -1 and end_index != -1 and end_index > start_index:
        end_index += len(marker_end)
        updated = (
            appendix_text[:start_index].rstrip()
            + "\n\n"
            + block
            + "\n"
            + appendix_text[end_index:].lstrip()
        )
        return updated, "replaced"

    if INSERT_BEFORE_HEADING in appendix_text:
        updated = appendix_text.replace(
            INSERT_BEFORE_HEADING, block + "\n\n" + INSERT_BEFORE_HEADING, 1
        )
        return updated, "inserted_before_extraction"

    if appendix_text and not appendix_text.endswith("\n"):
        appendix_text += "\n"
    updated = appendix_text + "\n" + block + "\n"
    return updated, "appended"


def build_summary(
    *,
    appendix_path: Path,
    latex_output_path: Path,
    analysis_latex_output_path: Path,
    decision_log_path: Path,
    analysis_trace_path: Path,
    rows_logged: int,
    analysis_outcomes_logged: int,
    decision_mode: str,
    analysis_mode: str,
) -> str:
    generated_at = datetime.now().strftime("%Y-%m-%d %H:%M")
    lines: list[str] = []
    lines.append("# Transparency Appendix Decision Trace Sync")
    lines.append("")
    lines.append(f"Generated: {generated_at}")
    lines.append("")
    lines.append("## I/O")
    lines.append("")
    lines.append(f"- Appendix: `{appendix_path.as_posix()}`")
    lines.append(f"- LaTeX table: `{latex_output_path.as_posix()}`")
    lines.append(f"- Analysis LaTeX table: `{analysis_latex_output_path.as_posix()}`")
    lines.append(f"- Decision log: `{decision_log_path.as_posix()}`")
    lines.append(f"- Analysis trace: `{analysis_trace_path.as_posix()}`")
    lines.append("")
    lines.append("## Result")
    lines.append("")
    lines.append(f"- Decision block mode: `{decision_mode}`")
    lines.append(f"- Analysis block mode: `{analysis_mode}`")
    lines.append(f"- Decision rows exported: {rows_logged}")
    lines.append(f"- Analysis outcomes exported: {analysis_outcomes_logged}")
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Sync auto-generated decision-trace section in appendix_transparency.md from decision_log.csv"
    )
    parser.add_argument(
        "--appendix",
        default="../appendix_transparency.md",
        help="Path to appendix markdown",
    )
    parser.add_argument(
        "--decision-log",
        default="../02_data/processed/decision_log.csv",
        help="Path to decision trace CSV",
    )
    parser.add_argument(
        "--summary-output",
        default="outputs/transparency_appendix_decision_trace_summary.md",
        help="Path to sync summary markdown",
    )
    parser.add_argument(
        "--analysis-trace",
        default="outputs/analysis_trace.json",
        help="Path to analysis trace JSON",
    )
    parser.add_argument(
        "--latex-output",
        default="../04_manuscript/tables/decision_trace_table.tex",
        help="Path to generated LaTeX decision-trace table",
    )
    parser.add_argument(
        "--analysis-latex-output",
        default="",
        help="Path to generated LaTeX analysis-trace table (default: alongside --latex-output as analysis_trace_table.tex)",
    )
    parser.add_argument(
        "--max-rows",
        type=int,
        default=50,
        help="Maximum decision rows to render in appendix table",
    )
    parser.add_argument(
        "--latex-max-rows",
        type=int,
        default=25,
        help="Maximum decision rows to render in LaTeX table",
    )
    parser.add_argument(
        "--analysis-max-rows",
        type=int,
        default=25,
        help="Maximum analysis outcome rows to render in appendix table",
    )
    parser.add_argument(
        "--analysis-latex-max-rows",
        type=int,
        default=25,
        help="Maximum analysis outcome rows to render in LaTeX table",
    )
    args = parser.parse_args(argv)

    appendix_path = Path(args.appendix)
    latex_output_path = Path(args.latex_output)
    analysis_latex_output_path = (
        Path(args.analysis_latex_output)
        if normalize(args.analysis_latex_output)
        else latex_output_path.with_name("analysis_trace_table.tex")
    )
    decision_log_path = Path(args.decision_log)
    analysis_trace_path = Path(args.analysis_trace)
    summary_path = Path(args.summary_output)

    if args.max_rows <= 0:
        raise SystemExit("--max-rows must be > 0")
    if args.latex_max_rows <= 0:
        raise SystemExit("--latex-max-rows must be > 0")
    if args.analysis_max_rows <= 0:
        raise SystemExit("--analysis-max-rows must be > 0")
    if args.analysis_latex_max_rows <= 0:
        raise SystemExit("--analysis-latex-max-rows must be > 0")

    try:
        decision_df = pd.read_csv(decision_log_path, dtype=str)
    except FileNotFoundError:
        raise SystemExit(f"Decision log not found: {decision_log_path.as_posix()}")
    except pd.errors.EmptyDataError:
        decision_df = pd.DataFrame()
    except pd.errors.ParserError as exc:
        raise SystemExit(f"Decision log CSV parsing failed: {exc}")

    required_columns = {"record_id", "stage", "decision", "reason", "reviewer"}
    missing = [column for column in required_columns if column not in decision_df.columns]
    if missing:
        raise SystemExit("Decision log is missing required columns: " + ", ".join(sorted(missing)))

    decision_log_display = "02_data/processed/decision_log.csv"
    block = build_decision_trace_block(
        decision_df,
        decision_log_path_display=decision_log_display,
        max_rows=args.max_rows,
    )

    analysis_trace_display = "03_analysis/outputs/analysis_trace.json"
    analysis_trace_payload, analysis_trace_status = load_analysis_trace_payload(analysis_trace_path)
    analysis_block, analysis_outcomes_logged = build_analysis_trace_block(
        analysis_trace_payload,
        source_display=analysis_trace_display,
        status=analysis_trace_status,
        max_rows=args.analysis_max_rows,
    )

    appendix_text = ""
    if appendix_path.exists():
        appendix_text = appendix_path.read_text(encoding="utf-8")

    updated_text, decision_mode = update_appendix_text(
        appendix_text,
        block,
        marker_start=MARKER_START,
        marker_end=MARKER_END,
    )
    updated_text, analysis_mode = update_appendix_text(
        updated_text,
        analysis_block,
        marker_start=ANALYSIS_MARKER_START,
        marker_end=ANALYSIS_MARKER_END,
    )

    appendix_path.parent.mkdir(parents=True, exist_ok=True)
    appendix_path.write_text(updated_text, encoding="utf-8")

    latex_table_text = build_latex_decision_trace_table(
        decision_df,
        decision_log_path_display=decision_log_path.as_posix(),
        max_rows=args.latex_max_rows,
    )
    latex_output_path.parent.mkdir(parents=True, exist_ok=True)
    latex_output_path.write_text(latex_table_text, encoding="utf-8")

    analysis_latex_text = build_latex_analysis_trace_table(
        analysis_trace_payload,
        source_display=analysis_trace_path.as_posix(),
        status=analysis_trace_status,
        max_rows=args.analysis_latex_max_rows,
    )
    analysis_latex_output_path.parent.mkdir(parents=True, exist_ok=True)
    analysis_latex_output_path.write_text(analysis_latex_text, encoding="utf-8")

    summary_text = build_summary(
        appendix_path=appendix_path,
        latex_output_path=latex_output_path,
        analysis_latex_output_path=analysis_latex_output_path,
        decision_log_path=decision_log_path,
        analysis_trace_path=analysis_trace_path,
        rows_logged=int(non_empty_rows(decision_df).shape[0]),
        analysis_outcomes_logged=analysis_outcomes_logged,
        decision_mode=decision_mode,
        analysis_mode=analysis_mode,
    )
    summary_path.parent.mkdir(parents=True, exist_ok=True)
    summary_path.write_text(summary_text, encoding="utf-8")

    print(f"Wrote: {appendix_path.as_posix()}")
    print(f"Wrote: {latex_output_path.as_posix()}")
    print(f"Wrote: {analysis_latex_output_path.as_posix()}")
    print(f"Wrote: {summary_path.as_posix()}")
    print(f"Decision rows exported: {int(non_empty_rows(decision_df).shape[0])}")
    print(f"Analysis outcomes exported: {analysis_outcomes_logged}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
