from __future__ import annotations

from .builder import (
    DraftArtifacts,
    DraftBuildContext,
    build_draft_artifacts,
    build_prefill_fields,
    build_submission_context,
)
from .field_composition import field_value_map, is_required_in_mode, prospero_field_templates
from .formatting import (
    collapse_whitespace,
    extract_braced_content,
    extract_latex_macro_argument,
    latex_to_plain,
    strip_latex_macro_with_argument,
    strip_markdown_markup,
)
from .io import (
    load_autofill_profile,
    read_protocol_text,
    resolve_cli_paths,
    resolve_preset_manuscript_path,
    write_text_artifact,
)
from .models import (
    ManuscriptMetadata,
    MarkdownSection,
    PrefillField,
    ProsperoFieldTemplate,
    ProtocolData,
)
from .rules import (
    auto_complete_missing_required_fields,
    completion_counts,
    default_placeholder_replacements,
    evaluate_exit_conditions,
    field_notes_for_missing,
    finalize_fields,
    infer_default_completion_date,
    infer_default_start_date,
    merge_placeholder_replacements,
    normalize_placeholder_token,
    parse_date_label_to_iso,
    placeholder_token_variants,
    replace_placeholders,
    required_scope_label,
    unresolved_placeholders_in_fields,
)

__all__ = [
    "DraftArtifacts",
    "DraftBuildContext",
    "ManuscriptMetadata",
    "MarkdownSection",
    "PrefillField",
    "ProsperoFieldTemplate",
    "ProtocolData",
    "auto_complete_missing_required_fields",
    "build_draft_artifacts",
    "build_prefill_fields",
    "build_submission_context",
    "collapse_whitespace",
    "completion_counts",
    "default_placeholder_replacements",
    "evaluate_exit_conditions",
    "field_value_map",
    "is_required_in_mode",
    "prospero_field_templates",
    "extract_braced_content",
    "extract_latex_macro_argument",
    "field_notes_for_missing",
    "finalize_fields",
    "infer_default_completion_date",
    "infer_default_start_date",
    "latex_to_plain",
    "load_autofill_profile",
    "merge_placeholder_replacements",
    "normalize_placeholder_token",
    "parse_date_label_to_iso",
    "placeholder_token_variants",
    "read_protocol_text",
    "replace_placeholders",
    "required_scope_label",
    "resolve_cli_paths",
    "resolve_preset_manuscript_path",
    "strip_latex_macro_with_argument",
    "strip_markdown_markup",
    "unresolved_placeholders_in_fields",
    "write_text_artifact",
]
