from __future__ import annotations

from datetime import datetime
from pathlib import Path


def latex_escape(value: object) -> str:
    text = str(value if value is not None else "").strip()
    if text.lower() == "nan":
        text = ""

    text = text.replace("\n", " ").replace("\r", " ")
    text = text.replace("\\", "\\textbackslash{}")
    text = text.replace("&", "\\&")
    text = text.replace("%", "\\%")
    text = text.replace("$", "\\$")
    text = text.replace("#", "\\#")
    text = text.replace("_", "\\_")
    text = text.replace("{", "\\{")
    text = text.replace("}", "\\}")
    text = text.replace("~", "\\textasciitilde{}")
    text = text.replace("^", "\\textasciicircum{}")
    return text


def render_table_block(
    *,
    generator_name: str,
    source_path: Path,
    caption: str,
    label: str,
    column_spec: str,
    headers: list[str],
    rows: list[list[str]],
    empty_row_latex: str,
    pre_tabular_lines: list[str] | None = None,
) -> str:
    generated_at = datetime.now().strftime("%Y-%m-%d %H:%M")
    lines = [
        f"% Auto-generated by {generator_name}",
        f"% Source: {source_path.as_posix()}",
        f"% Generated: {generated_at}",
        r"\begin{table}[htbp]",
        r"\centering",
        rf"\caption{{{caption}}}",
        rf"\label{{{label}}}",
    ]
    lines.extend(pre_tabular_lines or [])
    lines.extend(
        [
            rf"\begin{{tabular}}{{{column_spec}}}",
            r"\toprule",
            " & ".join(latex_escape(header) for header in headers) + r" \\",
            r"\midrule",
        ]
    )

    if rows:
        for row in rows:
            lines.append(" & ".join(latex_escape(cell) for cell in row) + r" \\")
    else:
        lines.append(empty_row_latex)

    lines.extend([r"\bottomrule", r"\end{tabular}", r"\end{table}", ""])
    return "\n".join(lines)
