import argparse
from datetime import datetime
from pathlib import Path

import pandas as pd


MISSING_VALUES = {
    "",
    "nan",
    "na",
    "n/a",
    "nr",
    "none",
    "unclear",
    "missing",
    "not reported",
    "not_reported",
    "not applicable",
    "not_applicable",
}

PRISMA_ROWS = [
    ("records_identified_databases", "Records identified from databases"),
    ("records_identified_other_sources", "Records identified from other sources"),
    ("duplicates_removed", "Duplicates removed"),
    ("records_screened_title_abstract", "Records screened (title/abstract)"),
    ("records_excluded_title_abstract", "Records excluded (title/abstract)"),
    ("reports_sought_for_retrieval", "Reports sought for retrieval"),
    ("reports_not_retrieved", "Reports not retrieved"),
    ("reports_assessed_full_text", "Reports assessed for eligibility (full text)"),
    ("reports_excluded_full_text", "Reports excluded (full text)"),
    ("studies_included_qualitative_synthesis", "Studies included in qualitative synthesis"),
    (
        "studies_included_quantitative_synthesis",
        "Studies included in quantitative synthesis (if applicable)",
    ),
]


def normalize(value: object) -> str:
    text = str(value if value is not None else "").strip()
    return "" if text.lower() == "nan" else text


def is_missing(value: object) -> bool:
    return normalize(value).lower() in MISSING_VALUES


def latex_escape(value: str) -> str:
    text = value.replace("\n", " ").replace("\r", " ")
    text = text.replace("\\", "\\textbackslash{}")
    text = text.replace("&", "\\&")
    text = text.replace("%", "\\%")
    text = text.replace("$", "\\$")
    text = text.replace("#", "\\#")
    text = text.replace("_", "\\_")
    text = text.replace("{", "\\{")
    text = text.replace("}", "\\}")
    text = text.replace("~", "\\textasciitilde{}")
    text = text.replace("^", "\\textasciicircum{}")
    return text


def read_csv_or_empty(path: Path, columns: list[str]) -> pd.DataFrame:
    if not path.exists():
        return pd.DataFrame(columns=columns)
    try:
        df = pd.read_csv(path, dtype=str)
    except pd.errors.EmptyDataError:
        return pd.DataFrame(columns=columns)

    for column in columns:
        if column not in df.columns:
            df[column] = ""
    return df


def count_display(value: object) -> str:
    text = normalize(value)
    if is_missing(text):
        return "---"

    numeric = pd.to_numeric(pd.Series([text]), errors="coerce").iloc[0]
    if pd.notna(numeric):
        numeric_float = float(numeric)
        if numeric_float.is_integer():
            return str(int(numeric_float))
        return f"{numeric_float:g}"

    return text


def render_prisma_table(prisma_df: pd.DataFrame, input_path: Path) -> str:
    generated_at = datetime.now().strftime("%Y-%m-%d %H:%M")

    stage_to_count: dict[str, object] = {}
    for _, row in prisma_df.iterrows():
        stage = normalize(row.get("stage", ""))
        if stage:
            stage_to_count[stage] = row.get("count", "")

    lines: list[str] = []
    lines.append("% Auto-generated by 03_analysis/prisma_tables.py")
    lines.append(f"% Source: {input_path.as_posix()}")
    lines.append(f"% Generated: {generated_at}")
    lines.append(r"\begin{table}[htbp]")
    lines.append(r"\centering")
    lines.append(r"\caption{PRISMA 2020 flow counts (auto-generated)}")
    lines.append(r"\label{tab:prisma_counts}")
    lines.append(r"\begin{tabular}{p{0.72\textwidth}r}")
    lines.append(r"\toprule")
    lines.append(r"Flow item & n \\")
    lines.append(r"\midrule")

    for stage, label in PRISMA_ROWS:
        count_text = count_display(stage_to_count.get(stage, ""))
        lines.append(f"{latex_escape(label)} & {latex_escape(count_text)} \\\\")

    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")
    lines.append(r"\end{table}")
    lines.append("")
    return "\n".join(lines)


def render_fulltext_table(fulltext_df: pd.DataFrame, input_path: Path) -> str:
    generated_at = datetime.now().strftime("%Y-%m-%d %H:%M")

    rows: list[tuple[str, str]] = []
    for _, row in fulltext_df.iterrows():
        reason = normalize(row.get("reason", ""))
        if is_missing(reason):
            continue
        count = count_display(row.get("count", ""))
        rows.append((reason, count))

    lines: list[str] = []
    lines.append("% Auto-generated by 03_analysis/prisma_tables.py")
    lines.append(f"% Source: {input_path.as_posix()}")
    lines.append(f"% Generated: {generated_at}")
    lines.append(r"\begin{table}[htbp]")
    lines.append(r"\centering")
    lines.append(r"\caption{Full-text exclusion reasons (auto-generated)}")
    lines.append(r"\label{tab:fulltext_exclusion}")
    lines.append(r"\begin{tabular}{p{0.72\textwidth}r}")
    lines.append(r"\toprule")
    lines.append(r"Reason & n \\")
    lines.append(r"\midrule")

    if rows:
        for reason, count in rows:
            lines.append(f"{latex_escape(reason)} & {latex_escape(count)} \\\\")
    else:
        lines.append(r"No full-text exclusion reasons logged yet. & --- \\")

    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")
    lines.append(r"\end{table}")
    lines.append("")
    return "\n".join(lines)


def render_summary(
    *,
    prisma_input: Path,
    fulltext_input: Path,
    prisma_output: Path,
    fulltext_output: Path,
    prisma_rows: int,
    fulltext_rows: int,
) -> str:
    generated_at = datetime.now().strftime("%Y-%m-%d %H:%M")

    lines: list[str] = []
    lines.append("# PRISMA Tables Summary")
    lines.append("")
    lines.append(f"Generated: {generated_at}")
    lines.append("")
    lines.append("## Inputs/Outputs")
    lines.append("")
    lines.append(f"- PRISMA counts input: `{prisma_input.as_posix()}`")
    lines.append(f"- Full-text reasons input: `{fulltext_input.as_posix()}`")
    lines.append(f"- PRISMA LaTeX output: `{prisma_output.as_posix()}`")
    lines.append(f"- Full-text LaTeX output: `{fulltext_output.as_posix()}`")
    lines.append("")
    lines.append("## Row Counts")
    lines.append("")
    lines.append(f"- PRISMA rows read: {prisma_rows}")
    lines.append(f"- Full-text reason rows read: {fulltext_rows}")
    lines.append("")
    lines.append("## Notes")
    lines.append("")
    lines.append("- Missing counts are rendered as `---`.")
    lines.append("- Table row order follows manuscript/PRISMA conventions.")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate manuscript PRISMA LaTeX tables from processed CSV files.")
    parser.add_argument(
        "--prisma-input",
        default="../02_data/processed/prisma_counts_template.csv",
        help="Path to PRISMA counts CSV",
    )
    parser.add_argument(
        "--fulltext-input",
        default="../02_data/processed/full_text_exclusion_reasons.csv",
        help="Path to full-text exclusion reasons CSV",
    )
    parser.add_argument(
        "--prisma-output",
        default="../04_manuscript/tables/prisma_counts_table.tex",
        help="Path to generated PRISMA counts LaTeX table",
    )
    parser.add_argument(
        "--fulltext-output",
        default="../04_manuscript/tables/fulltext_exclusion_table.tex",
        help="Path to generated full-text exclusion LaTeX table",
    )
    parser.add_argument(
        "--summary-output",
        default="outputs/prisma_tables_summary.md",
        help="Path to markdown summary",
    )
    args = parser.parse_args()

    prisma_input_path = Path(args.prisma_input)
    fulltext_input_path = Path(args.fulltext_input)
    prisma_output_path = Path(args.prisma_output)
    fulltext_output_path = Path(args.fulltext_output)
    summary_output_path = Path(args.summary_output)

    prisma_df = read_csv_or_empty(prisma_input_path, columns=["stage", "count", "notes"])
    fulltext_df = read_csv_or_empty(fulltext_input_path, columns=["reason", "count", "notes"])

    prisma_tex = render_prisma_table(prisma_df, input_path=prisma_input_path)
    fulltext_tex = render_fulltext_table(fulltext_df, input_path=fulltext_input_path)

    prisma_output_path.parent.mkdir(parents=True, exist_ok=True)
    prisma_output_path.write_text(prisma_tex, encoding="utf-8")

    fulltext_output_path.parent.mkdir(parents=True, exist_ok=True)
    fulltext_output_path.write_text(fulltext_tex, encoding="utf-8")

    summary_text = render_summary(
        prisma_input=prisma_input_path,
        fulltext_input=fulltext_input_path,
        prisma_output=prisma_output_path,
        fulltext_output=fulltext_output_path,
        prisma_rows=int(prisma_df.shape[0]),
        fulltext_rows=int(fulltext_df.shape[0]),
    )
    summary_output_path.parent.mkdir(parents=True, exist_ok=True)
    summary_output_path.write_text(summary_text, encoding="utf-8")

    print(f"Wrote: {prisma_output_path}")
    print(f"Wrote: {fulltext_output_path}")
    print(f"Wrote: {summary_output_path}")


if __name__ == "__main__":
    main()